### ISSUE TITLE
Voice starvation everytime Wwise remotely connects to Unity

### ISSUE THREAD

**Issue by adrianbarahona** [googlevr/gvr-audio-wwise-sdk#6] opened 2017-05-29 22:29 UTC
Hello,

Everytime I remotely connect Wwise to Unity I get a "Voice Starvation" error message. The audio is being spatialized correctly until I try to connect it to Wwise in real time.

I'm using Unity 5.6.1f1, Wwise v2016.2.3 and the GVR Audio Wwise SDK v0.4.0.

Any thoughts on this issue?

Thanks a lot.

**Comment by anokta** [comment] 2017-05-31 09:09
Hi,

Thanks for reporting the issue. FYI, the voice starvation error is expected due to the initial connection overhead when you first connect to the Wwise Authoring app.

However, I can indeed reproduce the issue locally where the audio stops once you remotely connect Wwise in run time. This seems to be a bug in our initialization routine, we are currently investigating this to fix the issue asap. Sorry for the inconvenience.

Cheers

**Comment by adrianbarahona** [comment] 2017-05-31 09:49
Hello,

Thanks a lot for taking the time to fix it.
Cheers!

**Comment by jkammerl** [comment] 2017-06-22 19:17
This bug has been fixed in our v0.5.0 release

**Closed as completed by jkammerl** 2017-06-22 19:17 UTC
